//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChartInASPMVC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighChart_Employee
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
    }
}
